[workspace]
members = [
    "base_rpc_client",
    "borrowers_indexer",
    "database_manager",
    "health_factor_service",
    "user_helper",
]
resolver = "2"

[profile.release]
opt-level = 3
rpath = true
lto = true
codegen-units = 1
panic = "abort"
