[package]
name = "database_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
libsql = "0.5.0"
chrono = "0.4.38"
lazy_static = "1.5.0"

[dev-dependencies]
tokio = { version = "1.39.0", features = ["rt"] }
